(function(){
 const role=document.body.dataset.nlamsRole; if(!role) return;
 const base=window.NLAMS_INTEGRATION_URL||'http://127.0.0.1:8090';
 const css=`.nlams-auto{position:fixed;right:18px;bottom:18px;z-index:99999;font:12px Arial;color:#213547}.nlams-auto>button{border:0;border-radius:999px;padding:11px 16px;background:#173b57;color:#fff;box-shadow:0 6px 22px #0003;cursor:pointer;font-weight:700}.nlams-auto .panel{display:none;width:430px;max-height:78vh;overflow:auto;background:#fff;border:1px solid #dce5ea;border-radius:14px;box-shadow:0 18px 55px #0003;margin-bottom:9px}.nlams-auto.open .panel{display:block}.nlams-auto .head{padding:14px;border-bottom:1px solid #e8eef1}.nlams-auto .head b{font-size:14px}.nlams-auto .tabs{display:flex;gap:4px;padding:8px;border-bottom:1px solid #e8eef1;overflow:auto}.nlams-auto .tabs button{border:0;background:#f1f5f8;color:#34566d;padding:7px 9px;border-radius:7px;white-space:nowrap;cursor:pointer;font-size:10px}.nlams-auto .tabs button.active{background:#2f6d9d;color:#fff}.nlams-auto .body{padding:12px}.nlams-auto .grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.nlams-auto .metric{padding:9px;background:#f7fafc;border:1px solid #e8eef1;border-radius:8px}.nlams-auto .metric b{display:block;font-size:17px}.nlams-auto .metric small{color:#6d7e8b}.nlams-auto .item{padding:10px 0;border-bottom:1px solid #edf1f3}.nlams-auto .item:last-child{border-bottom:0}.nlams-auto .item b{display:block}.nlams-auto .muted{color:#71818e}.nlams-auto .ok{color:#1c7b45}.nlams-auto .warn{color:#a86b00}.nlams-auto .bad{color:#b43a3a}.nlams-auto .pill{display:inline-block;padding:3px 6px;border-radius:999px;background:#eef4f8;margin:2px}.nlams-auto textarea,.nlams-auto select{width:100%;box-sizing:border-box;padding:8px;border:1px solid #ccd8df;border-radius:7px;margin:6px 0}.nlams-auto .actions{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.nlams-auto .actions button{border:0;padding:6px 9px;border-radius:6px;background:#eef4f8;color:#234b67;cursor:pointer}.nlams-auto .actions .primary{background:#2f6d9d;color:#fff}.nlams-auto .progress{height:7px;background:#edf2f5;border-radius:9px;overflow:hidden;margin:7px 0}.nlams-auto .progress span{display:block;height:100%;background:#2f6d9d}.nlams-auto .doc{display:flex;gap:8px;align-items:flex-start}.nlams-auto .doc input{margin-top:3px}`;
 const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
 const root=document.createElement('div');root.className='nlams-auto';root.innerHTML=`<div class="panel"><div class="head"><b>⚙ NLAMS Automation Center</b><div class="muted">Single case workflow · ${esc(role)}</div></div><div class="tabs"><button data-tab="overview" class="active">Overview</button><button data-tab="tasks">Tasks</button><button data-tab="docs">Documents</button><button data-tab="gis">GIS Evidence</button><button data-tab="notify">Notifications</button><button data-tab="audit">Audit</button><button data-tab="validate">Validation</button><button data-tab="health">Case Health</button><button data-tab="ai">AI Doc Guide</button></div><div class="body" id="nlamsAutoBody"></div></div><button>⚙ Automation <span id="nlamsAutoCount">0</span></button>`;document.body.appendChild(root);
 const body=root.querySelector('#nlamsAutoBody');
 root.children[1].onclick=()=>{root.classList.toggle('open');if(root.classList.contains('open'))load('overview')};
 root.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>load(b.dataset.tab));
 async function get(path){const r=await fetch(base+path);if(!r.ok)throw new Error((await r.json()).error||'Request failed');return r.json()}
 async function load(tab){root.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));body.innerHTML='<div class="muted">Loading automation…</div>';try{
  if(tab==='overview'){const s=await get('/api/automation/summary');root.querySelector('#nlamsAutoCount').textContent=s.pending_tasks+s.unread_notifications;body.innerHTML=`<div class="grid"><div class="metric"><b>${s.parcels}</b><small>Parcels</small></div><div class="metric"><b>${s.documents}</b><small>Documents</small></div><div class="metric"><b>${s.evidence}</b><small>GIS Evidence</small></div><div class="metric"><b>${s.pending_tasks}</b><small>Pending Tasks</small></div><div class="metric"><b>${s.unread_notifications}</b><small>Notifications</small></div><div class="metric"><b>${s.fully_verified}</b><small>Fully Verified</small></div></div><div class="item"><b>Automation chain</b><div class="muted">Project → Revenue → GIS → LAO → Compensation/R&R → Grievance → Admin</div></div><div class="actions"><button class="primary" onclick="window.NLAMSFlow.loadTab('health')">Open P-001 Case Health</button></div>`;}
  if(tab==='tasks'){const rows=await get('/api/automation/tasks?role='+encodeURIComponent(role));body.innerHTML=rows.length?rows.map(w=>`<div class="item"><b>${esc(w.ref)} · ${esc(w.title)}</b><div class="muted">${esc(w.status)} · ${esc(w.priority)} · Parcel ${esc(w.parcel_id||'—')}</div><div class="actions"><button class="primary" data-ref="${esc(w.ref)}" data-action="approve">Approve</button><button data-ref="${esc(w.ref)}" data-action="return">Return</button></div></div>`).join(''):'<div class="muted">No tasks assigned to this role.</div>';bindActions();}
  if(tab==='docs'){const c=await get('/api/case/P-001');body.innerHTML=`<div class="item"><b>Shared Document Registry · P-001</b><div class="muted">Project documents and parcel documents are visible to authorized portals without re-uploading.</div></div>`+c.documents.map(d=>`<div class="item"><b>📄 ${esc(d.name)}</b><span class="pill">${esc(d.category)}</span><span class="pill">v${esc(d.version)}</span><div class="muted">${esc(d.uploaded_by)} · ${esc(d.status)}</div></div>`).join('');}
  if(tab==='gis'){const c=await get('/api/case/P-001');body.innerHTML=`<div class="item"><b>GIS Evidence Registry · P-001 / Survey 125</b><div class="muted">Evidence remains attached to the same parcel record.</div></div>`+c.evidence.map(e=>`<div class="item"><b>📍 ${esc(e.name)}</b><div class="muted">${esc(e.evidence_type)} · ${esc(e.lat)} , ${esc(e.lng)}</div><span class="pill">${esc(e.label)}</span></div>`).join('');}
  if(tab==='notify'){const rows=await get('/api/automation/notifications?role='+encodeURIComponent(role));body.innerHTML=rows.length?rows.map(n=>`<div class="item"><b>${esc(n.title)}</b><div>${esc(n.message)}</div><div class="muted">${esc(n.created_at)} · ${esc(n.level)}</div></div>`).join(''):'<div class="muted">No notifications.</div>';}
  if(tab==='audit'){const rows=await get('/api/automation/audit?parcel_id=P-001');body.innerHTML=rows.length?rows.map(e=>`<div class="item"><b>${esc(e.action)}</b><div class="muted">${esc(e.actor)} · ${esc(e.from_role)} → ${esc(e.to_role)} · ${esc(e.at)}</div><div>${esc(e.note||'')}</div></div>`).join(''):'<div class="muted">No audit events.</div>';}
  if(tab==='validate'){const x=await get('/api/validation?parcel_id=P-001');body.innerHTML=x.checks.map(c=>`<div class="item"><b class="${c.status==='PASS'?'ok':'warn'}">${c.status==='PASS'?'✓':'⚠'} ${esc(c.rule)}</b><div>${esc(c.message)}</div></div>`).join('');}
  if(tab==='health'){const x=await get('/api/case-health?parcel_id=P-001');body.innerHTML=`<div class="item"><b>P-001 · Survey 125 · ${esc(x.parcel.status)}</b><div class="progress"><span style="width:${x.score}%"></span></div><b>${x.score}% Case Health · ${esc(x.risk)} Risk</b></div>`+x.checks.map(c=>`<div class="item"><b class="${c.status==='PASS'?'ok':'bad'}">${c.status==='PASS'?'✓':'✕'} ${esc(c.name)}</b></div>`).join('')+`<div class="muted">Documents: ${x.document_count} · Evidence: ${x.evidence_count}</div>`;}
  if(tab==='ai'){body.innerHTML=`<div class="item"><b>🤖 AI Document Guide</b><div class="muted">Describe the grievance/request. NLAMS suggests the relevant documents so the user does not have to guess. This prototype uses explainable rule-based AI-style classification; legal requirements remain officer-verified.</div><textarea id="nlamsAiText" placeholder="Example: My compensation has not been paid and I did not receive the award copy."></textarea><select id="nlamsAiCat"><option value="">Auto-detect category</option><option>Compensation</option><option>Possession</option><option>R&R</option><option>Land Record</option><option>Notification</option><option>GIS</option></select><button class="primary" id="nlamsAiRun">Generate Required Documents</button><div id="nlamsAiOut"></div></div>`;root.querySelector('#nlamsAiRun').onclick=async()=>{const text=root.querySelector('#nlamsAiText').value,cat=root.querySelector('#nlamsAiCat').value;const x=await get('/api/ai/document-guide?text='+encodeURIComponent(text)+'&category='+encodeURIComponent(cat));root.querySelector('#nlamsAiOut').innerHTML=`<div class="item"><b>Suggested checklist · ${Math.round(x.confidence*100)}% confidence</b>${x.documents.map(d=>`<div class="doc"><input type="checkbox" checked><div><b>${esc(d.name)}</b><div class="muted">${esc(d.why)}</div></div></div>`).join('')}</div><div class="muted">${esc(x.note)}</div>`};}
 }catch(e){body.innerHTML='<div class="bad">Automation service unavailable. Start START_ALL_NLAMS.bat and retry.</div>'}}
 function bindActions(){root.querySelectorAll('[data-ref]').forEach(b=>b.onclick=async()=>{const r=await fetch(base+'/api/workflow/'+encodeURIComponent(b.dataset.ref)+'/transition',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor_role:role,actor_name:document.title,action:b.dataset.action,note:'Action completed from NLAMS Automation Center.'})});const d=await r.json();alert(d.error||('Workflow updated. Next: '+d.current_role));load('tasks')})}
 function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 window.NLAMSFlow={load,loadTab:load};load('overview');
})();


/* NLAMS Secure Portal Layer - privacy, session awareness and automation hints */
(function(){
  if(window.__NLAMS_SECURE_LAYER)return; window.__NLAMS_SECURE_LAYER=true;
  const role=(document.body&&document.body.dataset&&document.body.dataset.nlamsRole)||'portal';
  const bar=document.createElement('div'); bar.id='nlams-security-bar'; bar.innerHTML='<span>🔒 <b>NLAMS Secure Mode</b> · Role-based access · Personal records protected</span><button id="nlamsPrivacyBtn" type="button">Data Privacy</button><span id="nlamsSession">Session active</span>';
  Object.assign(bar.style,{position:'fixed',left:'0',right:'0',bottom:'0',zIndex:'99999',background:'rgba(15,23,42,.97)',color:'#fff',padding:'8px 14px',display:'flex',gap:'16px',alignItems:'center',justifyContent:'center',fontSize:'12px',boxShadow:'0 -2px 12px rgba(0,0,0,.18)'});
  document.body.appendChild(bar);
  const btn=bar.querySelector('#nlamsPrivacyBtn'); Object.assign(btn.style,{background:'#fff',color:'#0f172a',border:0,borderRadius:'8px',padding:'5px 9px',cursor:'pointer',fontWeight:'700'});
  btn.onclick=async()=>{let d={version:'NLAMS-PRIVACY-v1.0',principles:['Purpose limitation','Role-based access','Minimum necessary data','Auditability','Secure document integrity','No public exposure of personal land records'],notice:'Personal and land information is used only for authentication, land-acquisition services, workflow processing and grievance handling. Demo records are synthetic.'}; try{d=await fetch('http://127.0.0.1:8090/api/privacy/policy').then(r=>r.json())}catch(e){} alert(d.title+'\nPolicy: '+d.version+'\n\n'+d.notice+'\n\nControls: '+d.principles.join(', '));};
  fetch('http://127.0.0.1:8090/api/security/heartbeat?role='+encodeURIComponent(role)).catch(()=>{});
  let last=Date.now(); ['click','keydown','mousemove','scroll'].forEach(e=>document.addEventListener(e,()=>last=Date.now(),{passive:true}));
  setInterval(()=>{const mins=Math.floor((Date.now()-last)/60000);bar.querySelector('#nlamsSession').textContent=mins>=25?'Session nearing timeout':'Session active';},30000);
})();
